precision: bf16-true
devices: 4
resume: false
seed: 1337
data:
  class_path: litgpt.data.AlpacaGPT4
  init_args:
    mask_prompt: false
    val_split_fraction: 0.03847
    prompt_style: "alpaca"
    ignore_index: -1
    seed: 42
    num_workers: 4
    download_dir: data/alpacagpt4
    file_url: https://raw.githubusercontent.com/Instruction-Tuning-with-GPT-4/GPT-4-LLM/main/data/alpaca_gpt4_data.json
    file_name: alpacagpt4_data_cleaned_archive.json
checkpoint_dir: checkpoints/meta-llama/Llama-2-7b-hf
out_dir: out/finetune/full-llama2-7b
train:
  save_interval: 200
  log_interval: 1
  global_batch_size: 64
  micro_batch_size: 4
  lr_warmup_steps: 25
  epochs: 1
  max_tokens: null
  max_steps: null
  max_seq_length: 512
  tie_embeddings: null
  learning_rate: 0.0002
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.95
  max_norm: null
  min_lr: 6.0e-05
eval:
  interval: 100
  max_new_tokens: 100
  max_iters: 100
